services:
  app:
    build: .
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
  nginx:
    image: nginx:alpine
    volumes:
      - ./public:/var/www/html/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - app
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_CHARSET: ${DB_CHARSET}
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - ${DB_PORT}:3306
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data: