services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.php
    depends_on:
      db:
        condition: service_healthy
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 8080:80
    depends_on:
      - app
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_CHARSET: ${DB_CHARSET}
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - ${DB_PORT}:3306
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root"]
      interval: 15s
      timeout: 5s
      retries: 20
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - 8081:80
volumes:
  db-data: